relay_chain: Polkadot
chain: Polkadot
wss: wss://polkadot-rpc.dwellir.com
databases:
  - type: bigquery
    project_id: project-id
    credentials_path: /path/to/credentials/file
    dataset: dataset
    table: table
ingest_mode: live  # live/historical
start_block: 1
end_block: 100