relay_chain: Polkadot
chain: Polkadot
wss: wss://polkadot-rpc.dwellir.com
databases:
  - type: mysql
    host: xx.xx.xx.xx
    port: 3306
    name: dotlake_sidecar_poc
    user: *****
    password: ******
ingest_mode: live  # live/historical
start_block: 1
end_block: 100