relay_chain: Polkadot
chain: Hydration
wss: wss://hydradx-rpc.dwellir.com
databases:
  - type: postgres
    host: xx.xx.xx.xx
    port: 5432
    name: dotlake_sidecar_poc
    user: ******
    password: *****
ingest_mode: live  # live/historical
start_block: 1
end_block: 100
