relay_chain: Polkadot
chain: Hydration
wss: wss://hydradx-rpc.dwellir.com
databases:
  - type: mysql
    host: xx.xx.xx.xx
    port: 3306
    name: dotlake_sidecar_poc
    user: *****
    password: ******