relay_chain: Polkadot
chain: Polkadot
wss: wss://polkadot-rpc.dwellir.com
create_db: false
retain_db: false 
databases:
  - type: postgres
    host: xx.xx.xx.xx
    port: 5432
    name: dotlake
    user: ******
    password: *****
ingest_mode: live  # live/historical
start_block: 1
end_block: 100
