relay_chain: Polkadot
chain: Hydration
wss: wss://hydradx-rpc.dwellir.com
databases:
  - type: mysql
    host: **.**.**.**
    port: 3306
    name: ****
    user: ****
    password: ***
ingest_mode: live  # live/historical
start_block: 1
end_block: 100
