# DotLake Configuration Example
# This file demonstrates the new improved configuration structure

# Chain Configuration
chain:
  relay_chain: Polkadot
  name: PolkadotAssetHub
  wss_endpoint: wss://polkadot-asset-hub-rpc.polkadot.io

# Ingest Configuration
ingest:
  mode: historical  # live | historical
  block_range:
    start: 9000000
    end: 9076000

# Database Configuration
database:
  # Option 1: Local database (creates PostgreSQL container)
  local:
    enabled: true
    retain_after_cleanup: false
    restore_from: null  # Path to backup file if restoring
  
  # Option 2: External database (uncomment and configure as needed)
  # external:
  #   enabled: true
  #   type: postgres  # postgres | mysql
  #   connection:
  #     host: host.docker.internal
  #     port: 5432
  #     name: dotlake
  #     user: username
  #     password: password 