relay_chain: Polkadot
chain: Hydration
wss: wss://hydradx-rpc.dwellir.com
databases:
  # - type: postgres
  #   host: 34.107.77.66
  #   port: 5432
  #   name: dotlake_sidecar_poc
  #   user: pranay
  #   password: postgresPassword
  - type: mysql
    host: 35.198.89.114
    port: 3306
    name: dotlake_sidecar_poc
    user: pranay
    password: mysqlPassword
  # - type: duckdb
  #   path: /path/to/duckdb/database
  # - type: mysql
  #   host: mysql_host
  #   port: 3306
  #   name: block_db
  #   user: mysql_user
  #   password: mysql_password
  # - type: bigquery
  #   project_id: parity-data-infra-evaluation
  #   credentials_path: /Users/pranaypatil/Downloads/parity-data-infra-evaluation-1d7b2ec60ac2.json
  #   dataset: pranay_playground
  #   table: blocks_hydration
