version: '3'
services:
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset_home:/app/superset_home
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    command: >
      bash -c "superset db upgrade &&
               superset init &&
               superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"