version: '3.8'

services:
  sidecar:
    container_name: dotlake_sidecar_instance
    image: parity/substrate-api-sidecar:latest
    read_only: true
    environment:
      - SAS_SUBSTRATE_URL=${WSS}
    ports:
      - "8080:8080"

  app:
    container_name: subindex-ingest
    image: python:3.9-slim
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      - RELAY_CHAIN=${RELAY_CHAIN}
      - CHAIN=${CHAIN}
      - WSS=${WSS}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PROJECT_ID=${PROJECT_ID}
      - CREDENTIALS_PATH=${CREDENTIALS_PATH}
      - DATASET=${DATASET}
      - TABLE=${TABLE}
      - INGEST_MODE=${INGEST_MODE}
      - START_BLOCK=${START_BLOCK} 
      - END_BLOCK=${END_BLOCK}
    volumes:
      - .:/app
    command: >
      bash -c "
        pip install -r requirements.txt &&
        chmod +x ./start-ingest.sh &&
        ./start-ingest.sh
      "

  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset_home:/app/superset_home
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    command: >
      bash -c "superset db upgrade &&
               superset init &&
               superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"


networks:
  default:
    name: dotlake_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16